# Generated by Django 5.2 on 2025-05-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.IntegerField(default=1),
        ),
    ]
