# Generated by Django 5.2 on 2025-05-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
